### ISSUE TITLE
error with ignored file

### ISSUE THREAD

**Issue by TrejGun** [kmagiera/babel-watch#112]
i have a file which i dont want to transpile so i added it to .babelignore and now my project fails to start with error

```
~/node_modules/babel-watch/babel-watch.js:388
  opts.babelrc = false;
               ^

TypeError: Cannot set property 'babelrc' of null
```

and when i use 

```
 --ignore server/file.ts
```
it throws another error
```
~/node_modules/babel-watch/babel-watch.js:377
    return babel.util.shouldIgnore(filename, ignore || [], only);
                      ^

TypeError: Cannot read property 'shouldIgnore' of undefined

```

**Comment by STRML** [comment]
Interesting. So the first case is expected if a file is ignored:

https://github.com/babel/babel/blob/f2af6c1170ebbea22bd29a2bae01efaec800dfe9/packages/babel-register/src/node.js#L50-L51

and we should update to handle it properly.

The second case is the same as #106 which was broken in babel 7 due to https://github.com/babel/babel/pull/5487.

@kmagiera I would like to continue maintaining this module but without publish access (or you publishing updates) - which I have been asking for, for 6+mo - none of the fixes I've committed can actually reach end users.

**Comment by TrejGun** [comment]
@STRML thanks for reply
can you publich your fork? like @STRML/babel-watch ?

**Comment by STRML** [comment]
Working on this now.

**Comment by STRML** [comment]
Fixed in `7.2.0`.

**Comment by TrejGun** [comment]
Thanks man! I'm happy this project got second life

**Comment by STRML** [comment]
Pew pew
