### ISSUE TITLE
add --require for preload module

### ISSUE THREAD

**Issue by ieow** [kmagiera/babel-watch#3]
some syntax require babel-polyfill which can be added via --require for node cmd

-r, --require         module to preload (option can be repeated)

**Comment by kmagiera** [comment]
Thanks @ieow for the suggestion. I may not have enough context on this one but think it would be better for the app itself to include the polyfill and here is why I think so (although l may be completely wrong in which case please correct me):
a) normally all the babel dependencies are linked as devDependencies which prevents them from being installed on the server. Since babel-polyfill needs to be loaded outside of dev mode too it should be added explicitly as the app "dependency" (otherwise it's too easy to forget polyfill should not only be a part of devDependencies)
b) last time I checked babel generated code didn't include require statement for the polyfill. Since on production it's not recommended to run the transpiler, you should pre-transpile your code in which case if polyfill is not required from your code it will not be loaded in production (the same problem is with libraries distributed over npmjs)

**Comment by ieow** [comment]
I think you are right.
Previously, I ended up on this preload module solution due to babel-node is already include the polyfill globaly.
This is causing me could not add require polyfill in the apps itself and resulting me using the preload module method for running babel built code

**Comment by alxlu** [comment]
`babel-polyfill` isn't the only package that uses the require flag. For instance, I'm trying to use `dotenv`: https://www.npmjs.com/package/dotenv 

`dotenv` goes into my devDependencies, and doesn't need to run on the server at all since the environment variables would already be set. It would make more sense here to be able to run `babel-watch -r dotenv/config src/index.js` over including it in the actual source.

**Comment by timkinnane** [comment]
I have the exact same issue as @alxlu - is this something worth re-opening? I can't use babel-watch because of this and am forced to use an extra line in my npm scripts. The humanity!

**Comment by alexkrautmann** [comment]
Same here. I am trying to use dotEnv and want to --require the environment loader file. Right now, I am requiring `./loadEnv.js` at the top of my entry point. However, this requires me to disable eslint/import rules. Its not the end of the world, but I don't like that the first thing people will see when they look at the source code is eslint disable rules.

**Comment by callumgare** [comment]
I also believe this is worth reopening. I'm wanting to use dotenv in exactly the same way.

**Comment by red-sight** [comment]
Currently you may use it in this way:
```
"scripts": {
    "dev": "BABEL_WATCH_NODE_OPTIONS='-r dotenv/config' babel-watch lib"
}
```
