### ISSUE TITLE
New files are not watched

### ISSUE THREAD

**Issue by azarus** [kmagiera/babel-watch#33]
I noticed that when i am adding a new file to the source, it doesn't really detect them. Any idea how to make it work?

**Comment by kmagiera** [comment]
Hey @azarus! Thanks for reporting! Would you be able to provide some more detailed description of the issue? Are you using autowatch? I understand that the newly added file is also linked with an existing/watched with require/import

**Comment by azarus** [comment]
Hey,
Sorry for the missing information.

I am using babel global import transform to import files globaly from a directory, but also updating a code and requiring external modules one by one. The watch fails to detect any newly added files, in any case as i experienced.

Launching babel-watch with existing files of app.js and a.js works.
**app.js**
`require("./a.js");`

**a.js**
`console.log("Hello world");`

But when adding a second file:

**b.js**
`console.log("Why u not work?");`

and adding this require("./b.js"); to **app.js** it does work too, because app.js was updated and the watch detected the file change, but if i update the new file the watch doesnt detect any changes. It requires a restart, i am guessing you're mapping the files upfront.

The other issue, is that if i use the global importer it just simply doesn't restart the app when adding new files, and the new files won't be imported.

**Comment by kmagiera** [comment]
@azarus I've tried following the steups you described and it works for me fine for me. Do you perhaps run babel-watch with some specific flags? Here is what I did:

 1. Created a project with app.js and a.js with the following content:
**app.js**
```
require('./a.js');
```
**a.js**
```
console.log("Hello from A");
```
 2. Run `babel-watch app.js`
 3. Create file `b.js` in the same location as `app.js` and `a.js` with the following content:
```
console.log("Hello from B");
```
 4. Add `require('./b.js')` to `app.js`
 5. See babel-watch restarts the app and `Hello from B` gets printed out
 6. Modify `b.js`
 7. Again, process restarts and changes are picked up


Is there something here that I'm missing? babel-watch dynamically adds new modules to the watching list as they are being added to the project.

Also please note that the file will start being watched only if it's "required" by another source file that is loaded. Otherwise if the file is not "required" there is no point in restarting the app as it means the file is not being used to run the app. Therefore it is needed that you update one of your source files first (e.g. add `require('./b);` to `app.js`)

**Comment by STRML** [comment]
Closing as stale.
